# Generated by Django 3.0.5 on 2021-01-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('thuc_hanh', models.BooleanField(default=True)),
                ('chi_ly_thuyet', models.IntegerField()),
                ('chi_thuc_hanh', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
