# Generated by Django 3.0.5 on 2021-01-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monhoc',
            name='ten',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
