# Generated by Django 3.0.5 on 2021-01-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0002_auto_20210117_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monhoc',
            name='thuc_hanh',
            field=models.BooleanField(default=False),
        ),
    ]
