# Generated by Django 3.0.5 on 2021-01-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0003_auto_20210117_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monhoc',
            old_name='chi_thuc_hanh',
            new_name='chi_th',
        ),
        migrations.RenameField(
            model_name='monhoc',
            old_name='chi_ly_thuyet',
            new_name='tong_chi',
        ),
    ]
